spring:
  application:
    name: auth-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: ${DB_PASSWORD:change_me}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:07e7d120437153c0a2b2f9578d7cce771a0ac48315388e76d868c68e5be36c7f}
  expiration: 86400000 # 24 hours in milliseconds

api:
  key:
    header: X-API-Key
    hmac-secret: ${API_KEY_HMAC_SECRET:change_me_in_production_use_a_strong_random_secret}

logging:
  level:
    com.pay.auth: DEBUG
    org.springframework.security: DEBUG