package com.paybridge.webhook.dto;

import com.paybridge.common.model.WebhookEventType;
import lombok.Builder;
import lombok.Data;

import java.time.Instant;

/**
 * Normalized webhook event for Kafka transport
 *
 * Purpose: Standardize provider-specific webhook formats into a common structure
 *
 * Why normalize?
 * - Paystack uses "charge.success"
 * - Interswitch uses "transaction.success"
 * - Our system uses PAYMENT_SUCCESS (enum)
 *
 * This DTO is what gets published to Kafka topic "webhook-events"
 */
@Data
@Builder
public class NormalizedWebhookEvent {

	/**
	 * Unique ID for this normalized event
	 * Format: UUID generated by webhook-service
	 */
	private String eventId;

	/**
	 * Reference to original webhook event in database
	 * Links back to webhook_events.id for audit trail
	 */
	private String originalWebhookId;

	/**
	 * Payment provider name
	 * Values: "paystack", "interswitch", "squadco"
	 */
	private String provider;

	/**
	 * Normalized event type (standardized across providers)
	 * Values: PAYMENT_SUCCESS, PAYMENT_FAILED, PAYMENT_PENDING, etc.
	 */
	private WebhookEventType eventType;

	/**
	 * Provider's transaction reference
	 * Used to find the payment transaction in payment-service
	 * Example: "txn_abc123xyz" (Paystack), "ISW_REF_123" (Interswitch)
	 */
	private String transactionReference;

	/**
	 * Full raw payload from provider (JSON string)
	 * Stored for audit trail and debugging
	 * Never modified after receipt
	 */
	private String rawPayload;

	/**
	 * Timestamp when webhook was received
	 * ISO 8601 format: "2024-01-15T12:34:56.789Z"
	 */
	private Instant receivedAt;

	/**
	 * Optional metadata for future extensibility
	 */
	private java.util.Map<String, Object> metadata;
}
